name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the sections below.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which AI tool are you using?
      options:
        - Claude Code
        - OpenCode
        - Codex CLI
        - Multiple platforms
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Run `npm list awesome-slash` or check package.json
      placeholder: "3.0.0"
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Command
      description: Which command triggered the issue?
      placeholder: "/next-task, /ship, /deslop, etc."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Run `/command`
        2. ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error output / logs
      description: Paste any error messages or relevant logs
      render: shell
    validations:
      required: false
